apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - name: metrics
          image: barbanera/practice:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_R2DBC_USERNAME
              value: "postgres"
            - name: SPRING_R2DBC_PASSWORD
              value: "mypassword"
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://postgres:5432/mydb"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/mydb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mypassword"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"