apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: default
spec:
  selector:
    app: metrics
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer