apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/local/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: practice-gitops