apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: practice-gitops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/arenabrab/practice-gitops